"""Core components of Py-dlp."""

from pydlp.core.cache import Cache
from pydlp.core.cookies import NetscapeCookieJar, build_cookie_header, parse_cookie_header
from pydlp.core.exceptions import (
    AuthenticationError,
    CancelRequested,
    DownloadError,
    ExtractorError,
    FormatNotAvailableError,
    GeoRestrictedError,
    LiveStreamError,
    NetworkError,
    PostProcessingError,
    PyDLPError,
    UnavailableVideoError,
    UnsupportedURLError,
)
from pydlp.core.format_selector import FormatFilter, FormatSelector, sort_formats
from pydlp.core.http import HttpClient, HttpResponse, RateLimiter
from pydlp.core.progress import (
    ConsoleProgressBar,
    ProgressHookDispatcher,
    SpeedCalculator,
    TerminalColors,
    colorize,
    format_table,
    print_format_table,
)
from pydlp.core.template import TemplateFormatter
from pydlp.core.types import (
    DownloadProgress,
    MediaChapter,
    MediaFormat,
    MediaInfo,
    MediaSubtitle,
    MediaThumbnail,
)
from pydlp.core.utils import (
    clean_html,
    determine_ext,
    float_or_none,
    format_bytes,
    format_seconds,
    format_speed,
    int_or_none,
    ordered_set,
    parse_duration,
    parse_filesize,
    parse_iso8601,
    parse_m3u8_attributes,
    sanitize_filename,
    str_or_none,
    try_get,
    unescape_html,
    urljoin,
)

__all__ = [
    "Cache",
    "NetscapeCookieJar",
    "build_cookie_header",
    "parse_cookie_header",
    "PyDLPError",
    "ExtractorError",
    "UnsupportedURLError",
    "DownloadError",
    "FormatNotAvailableError",
    "PostProcessingError",
    "NetworkError",
    "AuthenticationError",
    "GeoRestrictedError",
    "UnavailableVideoError",
    "LiveStreamError",
    "CancelRequested",
    "FormatFilter",
    "FormatSelector",
    "sort_formats",
    "HttpClient",
    "HttpResponse",
    "RateLimiter",
    "ConsoleProgressBar",
    "ProgressHookDispatcher",
    "SpeedCalculator",
    "TerminalColors",
    "colorize",
    "format_table",
    "print_format_table",
    "TemplateFormatter",
    "DownloadProgress",
    "MediaChapter",
    "MediaFormat",
    "MediaInfo",
    "MediaSubtitle",
    "MediaThumbnail",
    "clean_html",
    "determine_ext",
    "float_or_none",
    "format_bytes",
    "format_seconds",
    "format_speed",
    "int_or_none",
    "ordered_set",
    "parse_duration",
    "parse_filesize",
    "parse_iso8601",
    "parse_m3u8_attributes",
    "sanitize_filename",
    "str_or_none",
    "try_get",
    "unescape_html",
    "urljoin",
]
