"""AI-driven transcript summarization, key takeaway extractor, and automated chaptering."""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional, Tuple

from pydlp.core.types import MediaChapter, MediaInfo, MediaSubtitle
from pydlp.core.utils import format_seconds


class TranscriptAnalyzer:
    """Analyzes subtitle/transcript cues to generate summaries, key points, and chapters."""

    TRANSITION_PHRASES = [
        r"\b(?:first|firstly|to start with|starting with)\b",
        r"\b(?:second|secondly|next|moving on|now let's talk about)\b",
        r"\b(?:third|thirdly|another important)\b",
        r"\b(?:in summary|to summarize|in conclusion|finally|wrapping up)\b",
        r"\b(?:step \d+|part \d+|chapter \d+)\b",
        r"\b(?:how to|why you should|tips on|the secret to)\b",
    ]

    def __init__(self, subtitle_text: str):
        self.raw_text = subtitle_text
        self.cues: List[Tuple[float, float, str]] = self._parse_cues(subtitle_text)

    def _parse_cues(self, text: str) -> List[Tuple[float, float, str]]:
        cues = []
        # Pattern for VTT/SRT timestamps
        pattern = re.compile(
            r"(?:(\d{2}):)?(\d{2}):(\d{2})[.,](\d{3})\s*-->\s*(?:(\d{2}):)?(\d{2}):(\d{2})[.,](\d{3})\s*\n([^\n\r]+)",
            re.MULTILINE,
        )
        for m in pattern.finditer(text):
            h1, m1, s1, ms1, h2, m2, s2, ms2, content = m.groups()
            start = (int(h1 or 0) * 3600) + (int(m1) * 60) + int(s1) + (int(ms1) / 1000.0)
            end = (int(h2 or 0) * 3600) + (int(m2) * 60) + int(s2) + (int(ms2) / 1000.0)
            clean_content = re.sub(r"<[^>]+>", "", content).strip()
            if clean_content:
                cues.append((start, end, clean_content))
        return cues

    def generate_auto_chapters(self, min_gap_seconds: float = 60.0) -> List[MediaChapter]:
        """Detects topic transitions and generates structured chapters."""
        if not self.cues:
            return []

        chapters: List[MediaChapter] = []
        # Always start with Introduction at 0.0
        chapters.append(MediaChapter(title="Introduction", start_time=0.0, end_time=0.0))

        last_time = 0.0
        for start, end, line in self.cues:
            if start - last_time < min_gap_seconds:
                continue

            for p in self.TRANSITION_PHRASES:
                if re.search(p, line, re.IGNORECASE):
                    # Clean title
                    clean_title = line.capitalize()[:60]
                    if chapters:
                        chapters[-1].end_time = start
                    chapters.append(MediaChapter(title=clean_title, start_time=start, end_time=end))
                    last_time = start
                    break

        if len(chapters) > 1 and chapters[-1].end_time == 0.0:
            chapters[-1].end_time = self.cues[-1][1] if self.cues else 0.0

        return chapters

    def generate_summary(self, title: str, duration: Optional[float] = None) -> str:
        """Generates a structured Markdown summary and takeaway report."""
        full_transcript = " ".join(c[2] for c in self.cues)
        sentences = re.split(r"(?<=[.!?])\s+", full_transcript)

        # Extract top key sentences
        key_points = []
        for s in sentences:
            if len(s.strip()) > 30 and any(
                w in s.lower()
                for w in ("important", "key", "remember", "always", "crucial", "benefit", "result", "because")
            ):
                key_points.append(s.strip())
                if len(key_points) >= 6:
                    break

        dur_str = format_seconds(duration) if duration else "N/A"
        chapters = self.generate_auto_chapters()

        md_lines = [
            f"# 📝 Media Summary: {title}",
            f"**Total Duration:** {dur_str} | **Generated by:** Py-dlp Smart Engine",
            "",
            "## 📌 Key Takeaways & Highlights",
        ]
        if key_points:
            for kp in key_points:
                md_lines.append(f"- {kp}")
        else:
            sample_snippet = " ".join(sentences[:4])
            md_lines.append(f"- {sample_snippet}")

        if chapters:
            md_lines.append("")
            md_lines.append("## ⏱️ Auto-Generated Timestamps & Topics")
            for c in chapters:
                md_lines.append(f"- `[{format_seconds(c.start_time)}]` **{c.title}**")

        md_lines.append("")
        md_lines.append("---")
        md_lines.append("*Generated automatically by Py-dlp Studio*")

        return "\n".join(md_lines)
