name: Bug Report
description: Report an issue or broken extractor with Py-dlp
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please verify that you are running the latest version of Py-dlp (`pydlp --version`) before reporting.

  - type: input
    id: version
    attributes:
      label: Py-dlp Version
      description: Run `pydlp --version` and paste output here
      placeholder: "2026.09.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description of Issue
      description: Explain what happened vs what was expected
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Complete Command Line Output
      description: Run the command with `--verbose` and paste the full log here
      render: shell
    validations:
      required: true
