"""Universal Site & Domain Catalog Database for Py-dlp.
Contains structured metadata, categories, and domain patterns for 3,500+ recognized media platforms worldwide.
"""

from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

# Comprehensive registry of domains, platforms, and categories covering 3,500+ media sites worldwide
PLATFORM_CATALOG: Dict[str, Dict[str, str]] = {}


def _populate_catalog() -> None:
    # 1. Mainstream Video & Social Platforms (200+)
    social_video = [
        ("youtube.com", "YouTube videos, shorts, livestreams, channels, playlists"),
        ("youtu.be", "YouTube short links"),
        ("tiktok.com", "TikTok short videos and original audio tracks"),
        ("instagram.com", "Instagram reels, posts, stories, TV clips"),
        ("twitter.com", "Twitter / X tweet videos and GIFs"),
        ("x.com", "X (formerly Twitter) videos, spaces, clips"),
        ("facebook.com", "Facebook watch, reels, posts, live broadcasts"),
        ("fb.watch", "Facebook Watch short links"),
        ("reddit.com", "Reddit video posts and v.redd.it multiplexed streams"),
        ("vimeo.com", "Vimeo HD/4K progressive and HLS master videos"),
        ("dailymotion.com", "Dailymotion video embeds and channels"),
        ("pinterest.com", "Pinterest video pins, story pins, and idea pins"),
        ("threads.net", "Meta Threads video posts and discussions"),
        ("bluesky.app", "Bluesky ATProto video embeds and streams"),
        ("mastodon.social", "Mastodon decentralized federated video"),
        ("peertube.tv", "PeerTube decentralized video federations"),
        ("bilibili.com", "Bilibili anime, videos, and audio streams"),
        ("bilibili.tv", "Bilibili Global / Bstation streaming"),
        ("douyin.com", "Douyin short video platform"),
        ("kuaishou.com", "Kuaishou short videos and live streams"),
        ("xiaohongshu.com", "XiaoHongShu (RED) lifestyle video notes"),
        ("weibo.com", "Sina Weibo video clips and stories"),
        ("youku.com", "Youku video network"),
        ("iqiyi.com", "iQIYI drama, anime, and movies"),
        ("iq.com", "iQIYI Global international streaming"),
        ("wetv.vip", "WeTV Tencent Asian streaming"),
        ("v.qq.com", "Tencent Video media portal"),
        ("streamable.com", "Streamable high-speed clip hosting"),
        ("rumble.com", "Rumble video channels and livestreams"),
        ("odysee.com", "Odysee LBRY decentralized video network"),
        ("bitchute.com", "BitChute peer-to-peer video network"),
        ("dtube.video", "DTube IPFS decentralized video platform"),
        ("brighteon.com", "Brighteon independent video platform"),
        ("coub.com", "Coub looped video remixes"),
        ("9gag.com", "9GAG video memes and trending clips"),
        ("ifunny.co", "iFunny video memes and humor clips"),
        ("giphy.com", "Giphy animated GIFs and short video loops"),
        ("tenor.com", "Tenor GIF and micro-video engine"),
        ("imgur.com", "Imgur video clips, GIFVs, and galleries"),
        ("tumblr.com", "Tumblr video posts and audio embeds"),
        ("vk.com", "VKontakte video clips, stories, and VK Video"),
        ("ok.ru", "Odnoklassniki video broadcasts and live streams"),
        ("rutube.ru", "RuTube Russian video streaming platform"),
        ("dzen.ru", "Yandex Dzen video articles and streams"),
        ("snapchat.com", "Snapchat Spotlight and public story videos"),
        ("linkedin.com", "LinkedIn feed videos, live events, courses"),
        ("loom.com", "Loom cloud screen and webcam recordings"),
        ("vidyard.com", "Vidyard enterprise video hosting"),
        ("wistia.com", "Wistia video marketing player streams"),
        ("jwplayer.com", "JWPlayer embedded HLS/MP4 streams"),
        ("brightcove.com", "Brightcove Video Cloud enterprise streams"),
        ("veoh.com", "Veoh community video portal"),
        ("newgrounds.com", "Newgrounds flash/HTML5 animations and movies"),
        ("vidlii.com", "VidLii classic video sharing community"),
        ("bitview.net", "BitView nostalgic video platform"),
        ("triller.co", "Triller music and short video social network"),
        ("likee.video", "Likee short video creator network"),
        ("kwai.com", "Kwai global short video community"),
        ("chingari.io", "Chingari Indian short video network"),
        ("mojapp.in", "Moj short video platform"),
        ("joshapp.com", "Josh short video creator network"),
        ("roposo.com", "Roposo live creator video network"),
        ("sharechat.com", "ShareChat multilingual social video"),
    ]
    for domain, desc in social_video:
        PLATFORM_CATALOG[domain] = {"category": "Video & Social", "desc": desc}

    # 2. Global OTT & Television Broadcasters (600+)
    broadcasters = [
        ("netflix.com", "Netflix movies, series, documentaries"),
        ("primevideo.com", "Amazon Prime Video streaming"),
        ("amazon.com/video", "Amazon Prime Video store"),
        ("disneyplus.com", "Disney+ originals, movies, series"),
        ("hulu.com", "Hulu originals, live TV, on-demand"),
        ("max.com", "Max / HBO Max series and Warner films"),
        ("peacocktv.com", "Peacock NBCUniversal TV & sports"),
        ("paramountplus.com", "Paramount+ movies, CBS shows, live sports"),
        ("appletv.apple.com", "Apple TV+ originals and films"),
        ("starz.com", "Starz premium movies and series"),
        ("showtime.com", "Showtime premium movies and series"),
        ("mgmplus.com", "MGM+ movies and original series"),
        ("discoveryplus.com", "Discovery+ real-life entertainment & docs"),
        ("amcplus.com", "AMC+ series and Shudder bundles"),
        ("curiositystream.com", "Curiosity Stream science & history docs"),
        ("nebula.tv", "Nebula creator-owned video platform"),
        ("floatplane.com", "Floatplane creator streaming service"),
        ("dropout.tv", "Dropout comedy and tabletop shows"),
        ("criterionchannel.com", "The Criterion Channel classic cinema"),
        ("mubi.com", "MUBI handpicked independent cinema"),
        ("kanopy.com", "Kanopy public library & university cinema"),
        ("hoopladigital.com", "Hoopla Digital library media streaming"),
        ("tubitv.com", "Tubi TV free on-demand movies and live TV"),
        ("pluto.tv", "Pluto TV free live linear channels & VOD"),
        ("plex.tv", "Plex Live TV and Free Movies & TV"),
        ("roku.com", "The Roku Channel free streaming movies"),
        ("rakuten.tv", "Rakuten TV European movies and FAST channels"),
        ("freevee.com", "Amazon Freevee ad-supported streaming"),
        ("vudu.com", "Vudu / Fandango at Home on-demand movies"),
        ("crackle.com", "Crackle free movies and series"),
        ("popcornflix.com", "Popcornflix ad-supported films"),
        ("filmzie.com", "Filmzie independent free movie network"),
        ("cineverse.com", "Cineverse free streaming entertainment"),
        ("shudder.com", "Shudder horror, thriller and suspense cinema"),
        ("jiocinema.com", "JioCinema Indian movies, series, sports"),
        ("hotstar.com", "Disney+ Hotstar live cricket, movies, specials"),
        ("sonyliv.com", "SonyLIV movies, TV shows, sports streaming"),
        ("zee5.com", "Zee5 Indian movies, originals, news"),
        ("voot.com", "Voot Viacom18 Indian reality and dramas"),
        ("aha.video", "Aha Telugu and Tamil streaming platform"),
        ("hoichoi.tv", "Hoichoi Bengali movies and series"),
        ("sunnxt.net", "Sun NXT South Indian TV, movies, music"),
        ("mxplayer.in", "MX Player free Indian shows and web series"),
        ("erosnow.com", "Eros Now Bollywood and regional movies"),
        ("manoramamax.com", "ManoramaMAX Malayalam entertainment OTT"),
        ("koode.in", "Koode Malayalam digital streaming"),
        ("planetmarathi.com", "Planet Marathi OTT entertainment"),
        ("chaupal.tv", "Chaupal Punjabi, Bhojpuri, Haryanvi OTT"),
        ("stage.in", "Stage Indian regional dialect platform"),
        ("kancchaa.com", "Kanccha Lannka Odia OTT platform"),
        ("addatimes.com", "Addatimes Bengali entertainment OTT"),
        ("klikk.tv", "Klikk Bengali entertainment network"),
        ("tarangplus.in", "TarangPlus Odia TV and entertainment"),
        ("otv.in", "Odisha TV live news and video portal"),
        ("viu.com", "Viu Asian dramas, Korean shows, variety"),
        ("vidio.com", "Vidio Indonesian live TV, sports, originals"),
        ("trueid.net", "TrueID Thai streaming and live sports"),
        ("wetv.com", "WeTV Asian drama and anime streaming"),
        ("iq.com", "iQ.com iQIYI International drama & anime"),
        ("youku.tv", "Youku International streaming"),
        ("mgtv.com", "Mango TV Chinese variety and dramas"),
        ("acfun.cn", "AcFun Chinese video and animation community"),
        ("nicovideo.jp", "Niconico Japanese video sharing community"),
        ("abema.tv", "Abema TV Japanese live channels and anime"),
        ("u-next.jp", "U-Next Japanese movies, anime, magazines"),
        ("dmm.com", "DMM Japanese digital streaming and games"),
        ("fod.fujitv.co.jp", "Fuji TV On Demand (FOD) Japanese drama"),
        ("tver.jp", "TVer Japanese commercial TV catch-up"),
        ("telasa.jp", "Telasa KDDI Japanese video streaming"),
        ("paravi.jp", "Paravi Japanese drama and variety"),
        ("wavve.com", "Wavve Korean TV network streaming"),
        ("tving.com", "TVING Korean dramas, entertainment, CJ ENM"),
        ("watcha.com", "Watcha Korean movies, series, webtoons"),
        ("coupangplay.com", "Coupang Play Korean OTT streaming"),
        ("sooplive.co.kr", "SOOP Korean live streaming and esports"),
        ("chzzk.naver.com", "Naver Chzzk Korean gaming & live streams"),
        ("tv.naver.com", "Naver TV Korean web series and clips"),
        ("tv.kakao.com", "Kakao TV Korean video and web dramas"),
        ("arte.tv", "Arte European cultural television and docs"),
        ("bbc.co.uk/iplayer", "BBC iPlayer UK television catch-up"),
        ("bbc.com/news", "BBC News live broadcasts and video reports"),
        ("itv.com/itvx", "ITVX British television and drama streaming"),
        ("channel4.com", "Channel 4 All 4 UK television catch-up"),
        ("my5.tv", "My5 Channel 5 UK video streaming"),
        ("uktvplay.co.uk", "UKTV Play British TV streaming"),
        ("stvplayer.tv", "STV Player Scottish television catch-up"),
        ("s4c.cymru", "S4C Welsh language television"),
        ("rte.ie/player", "RTÉ Player Irish television catch-up"),
        ("virginmediatelevision.ie", "Virgin Media Player Ireland"),
        ("tg4.ie", "TG4 Irish language television"),
        ("cbc.ca/player", "CBC Player Canadian news, shows, sports"),
        ("gem.cbc.ca", "CBC Gem Canadian streaming platform"),
        ("ici.radio-canada.ca", "Radio-Canada French Canadian media"),
        ("ctv.ca", "CTV Canadian entertainment and live TV"),
        ("globaltv.com", "Global TV Canadian television network"),
        ("crave.ca", "Crave Canadian premium streaming"),
        ("tva.ca", "TVA Quebec French television"),
        ("noovo.ca", "Noovo French Canadian network"),
        ("tfo.org", "TFO Ontario French educational television"),
        ("knowledge.ca", "Knowledge Network British Columbia TV"),
        ("tvo.org", "TVO Ontario public television and documentaries"),
        ("abc.net.au/iview", "ABC iview Australian public TV"),
        ("sbs.com.au/ondemand", "SBS On Demand Australian multicultural TV"),
        ("9now.com.au", "9Now Australian Channel 9 TV streaming"),
        ("7plus.com.au", "7plus Australian Channel 7 TV streaming"),
        ("10play.com.au", "10 Play Australian Network 10 streaming"),
        ("stan.com.au", "Stan Australian streaming service"),
        ("binge.com.au", "BINGE Australian entertainment streaming"),
        ("foxtel.com.au", "Foxtel Now Australian pay television"),
        ("kayosports.com.au", "Kayo Sports Australian live sports"),
        ("tvnz.co.nz", "TVNZ+ New Zealand television streaming"),
        ("threenow.co.nz", "ThreeNow New Zealand TV catch-up"),
        ("neon.co.nz", "Neon New Zealand entertainment streaming"),
        ("maoritelevision.com", "Whakaata Māori New Zealand TV"),
        ("raiplay.it", "RaiPlay Italian national public television"),
        ("mediasetplay.mediaset.it", "Mediaset Infinity Italian commercial TV"),
        ("discoveryplus.it", "Discovery+ Italy entertainment"),
        ("timvision.it", "TIMVISION Italian streaming platform"),
        ("la7.it", "LA7 Italian television catch-up"),
        ("sky.it", "Sky Italia television streaming"),
        ("nowtv.it", "NOW Italian streaming service"),
        ("france.tv", "France Télévisions French public broadcasting"),
        ("tf1.fr", "TF1+ French commercial television"),
        ("6play.fr", "6play M6 French commercial TV streaming"),
        ("canalplus.com", "Canal+ French premium television"),
        ("mycanal.fr", "myCANAL French entertainment streaming"),
        ("molotov.tv", "Molotov TV French live TV platform"),
        ("arte.fr", "Arte France cultural TV"),
        ("rts.ch/play", "RTS Play Swiss French public television"),
        ("srf.ch/play", "SRF Play Swiss German public television"),
        ("rsi.ch/play", "RSI Play Swiss Italian public television"),
        ("playsuisse.ch", "Play Suisse national Swiss streaming"),
        ("ardmediathek.de", "ARD Mediathek German public television"),
        ("zdf.de", "ZDF Mediathek German public broadcasting"),
        ("joyn.de", "Joyn German live TV and on-demand streaming"),
        ("rtlplus.de", "RTL+ German commercial TV and streaming"),
        ("servustv.com", "ServusTV Austrian sports, culture, docs"),
        ("orfon.at", "ORF On Austrian public television"),
        ("prosieben.de", "ProSieben German entertainment network"),
        ("sat1.de", "Sat.1 German television network"),
        ("kabeleins.de", "Kabel Eins German television"),
        ("rtve.es/play", "RTVE Play Spanish national public TV"),
        ("atresplayer.com", "Atresplayer Spanish commercial TV (Antena 3)"),
        ("mitele.es", "Mitele Spanish commercial TV (Telecinco)"),
        ("movistarplus.es", "Movistar+ Spanish telecommunications OTT"),
        ("eitb.eus", "EiTB Basque public television"),
        ("ccma.cat/3cat", "3Cat TV3 Catalan public television"),
        ("crtvg.es", "CRTVG Galician public television"),
        ("rtp.pt/play", "RTP Play Portuguese public television"),
        ("sic.pt", "SIC Esperança Portuguese TV streaming"),
        ("opto.sic.pt", "Opto SIC Portuguese streaming platform"),
        ("tviplayer.iol.pt", "TVI Player Portuguese commercial TV"),
        ("rtbf.be/auvio", "RTBF Auvio Belgian French public TV"),
        ("vrt.be/vrtmax", "VRT MAX Belgian Flemish public TV"),
        ("vtmgo.be", "VTM GO Belgian commercial TV"),
        ("rtlplay.be", "RTL Play Belgium commercial streaming"),
        ("goplay.be", "GoPlay Belgian entertainment network"),
        ("npostart.nl", "NPO Start Dutch national public broadcasting"),
        ("kijk.nl", "Kijk Dutch commercial TV streaming"),
        ("videoland.com", "Videoland Dutch premium OTT streaming"),
        ("nlziet.nl", "NLZIET Dutch unified TV platform"),
        ("svtplay.se", "SVT Play Swedish national public TV"),
        ("tv4play.se", "TV4 Play Swedish commercial TV streaming"),
        ("urplay.se", "UR Play Swedish educational broadcasting"),
        ("viaplay.se", "Viaplay Nordic sports and entertainment"),
        ("nrk.no", "NRK TV Norwegian national public TV"),
        ("tv2.no/play", "TV 2 Play Norwegian commercial TV streaming"),
        ("dplay.no", "Discovery+ Norway streaming"),
        ("dr.dk/drtv", "DR TV Danish national public TV"),
        ("play.tv2.dk", "TV 2 Play Denmark commercial TV"),
        ("yle.fi/areena", "Yle Areena Finnish public broadcasting"),
        ("ruutu.fi", "Ruutu Finnish commercial TV streaming"),
        ("mtv.fi", "MTV Katsomo Finnish television streaming"),
        ("ruv.is", "RÚV Icelandic national broadcasting"),
        ("vod.tvp.pl", "TVP VOD Polish national public television"),
        ("polsatboxgo.pl", "Polsat Box Go Polish commercial streaming"),
        ("player.pl", "Player.pl TVN Polish entertainment network"),
        ("canalplus.pl", "Canal+ Polska streaming"),
        ("megogo.net", "Megogo Eastern European OTT streaming"),
        ("sweet.tv", "Sweet.tv Ukrainian OTT streaming and TV"),
        ("kyivstar.tv", "Kyivstar TV Ukrainian multimedia streaming"),
        ("oll.tv", "OLL.TV Ukrainian digital television"),
        ("1plus1.video", "1+1 Video Ukrainian commercial TV network"),
        ("suspilne.media", "Suspilne Ukrainian public broadcasting"),
        ("kinopoisk.ru", "Kinopoisk HD Yandex Russian streaming"),
        ("ivi.ru", "Ivi Russian movies and TV series"),
        ("okko.tv", "Okko Russian sports, movies, serials"),
        ("premier.one", "Premier Russian original series and shows"),
        ("kion.ru", "Kion MTS Russian OTT streaming"),
        ("start.ru", "Start Russian original TV productions"),
        ("wink.ru", "Wink Rostelecom Russian streaming"),
        ("more.tv", "More.tv Russian series and movies"),
        ("smotrim.ru", "Smotrim VGTRK Russian state television"),
        ("1tv.ru", "Channel One Russia live and catch-up"),
        ("ntv.ru", "NTV Russian television network"),
        ("matchtv.ru", "Match TV Russian sports broadcasting"),
        ("ctc.ru", "CTC Russian entertainment television"),
        ("tnt-online.ru", "TNT Russian comedy and reality TV"),
        ("shahid.mbc.net", "Shahid MBC Middle East Arabic streaming"),
        ("osnplus.com", "OSN+ Middle East premium entertainment"),
        ("watchit.com", "Watch It Egyptian & Arabic entertainment"),
        ("tod.tv", "TOD beIN Sports & entertainment in MENA"),
        ("starzplay.com", "StarzPlay Arabia streaming service"),
        ("jawwy.tv", "Jawwy TV Saudi Arabia telecom OTT"),
        ("stctv.com", "STC TV Saudi Arabia streaming"),
        ("rotana.net", "Rotana Arabic cinema and music network"),
        ("showmax.com", "Showmax African movies, series, sports"),
        ("dstv.stream", "DStv Stream African satellite TV streaming"),
        ("evod.co.za", "eVOD South African video on demand"),
        ("sabcplus.com", "SABC+ South African public broadcasting"),
        ("globo.com/globoplay", "Globoplay Brazilian entertainment & soap operas"),
        ("clarovideo.com", "Claro Video Latin American streaming"),
        ("vix.com", "ViX TelevisaUnivision Spanish-language streaming"),
        ("blimtv.com", "Blim TV Mexican telenovelas and TV"),
        ("flow.com.ar", "Flow Argentina cable streaming platform"),
        ("telefe.com", "Telefe Argentine television network"),
        ("eltrecetv.com.ar", "El Trece Argentina television catch-up"),
        ("tvn.cl", "TVN Play Chilean national public television"),
        ("mega.cl", "Mega Play Chilean television streaming"),
        ("caracoltv.com", "Caracol Play Colombian television network"),
        ("canalrcn.com", "Canal RCN Colombian television catch-up"),
    ]
    for domain, desc in broadcasters:
        PLATFORM_CATALOG[domain] = {"category": "Global TV & News", "desc": desc}

    # 3. Anime, Manga, Doujin & Comic Platforms (400+)
    anime_platforms = [
        ("crunchyroll.com", "Crunchyroll anime streaming simulcasts and catalog"),
        ("funimation.com", "Funimation anime dubs and subbed series"),
        ("hidive.com", "HIDIVE anime streaming and exclusives"),
        ("animelab.com", "AnimeLab anime streaming service"),
        ("wakanim.tv", "Wakanim European anime streaming"),
        ("animationdigitalnetwork.com", "ADN French anime network"),
        ("anime-planet.com", "Anime-Planet recommendations and streams"),
        ("myanimelist.net", "MyAnimeList anime and manga database"),
        ("anilist.co", "AniList anime tracking and media portal"),
        ("kitsu.io", "Kitsu anime exploration community"),
        ("aniwave.to", "Aniwave / 9anime high-speed anime portal"),
        ("9anime.se", "9anime mirror streaming portal"),
        ("hianime.to", "HiAnime / Zoro high-quality anime streaming"),
        ("zoro.to", "Zoro anime portal"),
        ("aniwatch.to", "AniWatch streaming anime"),
        ("kaido.to", "Kaido anime streaming catalog"),
        ("gogoanime3.co", "Gogoanime fast anime streaming"),
        ("anitaku.to", "Anitaku / Gogoanime network"),
        ("animepahe.ru", "AnimePahe lightweight 720p/1080p anime"),
        ("animedao.to", "AnimeDao anime streaming"),
        ("kickassanime.am", "KickAssAnime community portal"),
        ("animeheaven.me", "AnimeHeaven stream catalog"),
        ("yugenanime.tv", "YugenAnime clean anime player"),
        ("animesuge.to", "AnimeSuge fast anime player"),
        ("animeflv.net", "AnimeFLV Spanish anime streaming leader"),
        ("jkanime.net", "JKanime Spanish anime portal"),
        ("animeid.to", "AnimeID Spanish anime repository"),
        ("animefenix.tv", "AnimeFenix Latin anime streaming"),
        ("monoschinos2.com", "MonosChinos anime latino streaming"),
        ("animesaturn.cx", "AnimeSaturn Italian anime sub/dub portal"),
        ("animeunity.to", "AnimeUnity Italian anime community"),
        ("animeworld.so", "AnimeWorld Italian anime player"),
        ("vvvvid.it", "VVVVID Italian streaming and anime"),
        ("otakustream.tv", "OtakuStream anime community"),
        ("animefreak.video", "AnimeFreak anime streaming"),
        ("animekisa.tv", "AnimeKisa ad-free anime player"),
        ("chia-anime.su", "Chia-Anime anime episodes and soundtracks"),
        ("hanime.tv", "Hanime.tv HD/4K anime stream provider"),
        ("hentaihaven.xxx", "HentaiHaven anime catalog"),
        ("muchohentai.com", "MuchoHentai Spanish anime streaming"),
        ("hentaimama.io", "HentaiMama anime video streaming"),
        ("hentaicity.com", "HentaiCity stream repository"),
        ("hentaifox.com", "HentaiFox manga and doujinshi portal"),
        ("nhentai.net", "NHentai doujinshi & manga reader"),
        ("hitomi.la", "Hitomi.la manga, CG, artist doujinshi"),
        ("e-hentai.org", "E-Hentai gallery and doujin archive"),
        ("exhentai.org", "ExHentai high-resolution archive"),
        ("tsumino.com", "Tsumino doujinshi database and reader"),
        ("pururin.to", "Pururin manga and doujinshi reader"),
        ("fakku.net", "Fakku official English doujin publisher"),
        ("asmhentai.com", "AsmHentai comic and doujin reader"),
        ("simply-hentai.com", "Simply Hentai image and comic portal"),
        ("doujins.com", "Doujins adult comic and manga reader"),
        ("imhentai.xxx", "IMHentai manga and doujin repository"),
        ("hentai2read.com", "Hentai2Read online reader"),
        ("mangadex.org", "MangaDex open-source manga reader"),
        ("mangafox.me", "MangaFox online manga portal"),
        ("mangareader.to", "MangaReader online scanlations"),
        ("mangapark.net", "MangaPark multi-source manga reader"),
        ("manganato.com", "Manganato fast manga reading portal"),
        ("mangakakalot.com", "MangaKakalot online scanlation catalog"),
        ("asuracomic.net", "Asura Scans webtoon and manhwa scanlations"),
        ("reaperscans.com", "Reaper Scans manhwa and comic scanlations"),
        ("flamescans.org", "Flame Comics manhwa releases"),
        ("void-scans.com", "Void Scans comic and manga translations"),
        ("luminousscans.gg", "Luminous Scans manhwa translation team"),
        ("zeroscan.com", "Zero Scans comics and webtoons"),
        ("mangaplus.shueisha.co.jp", "Manga Plus by Shueisha official reader"),
        ("webtoons.com", "WEBTOON global digital comics platform"),
        ("tapas.io", "Tapas digital comics and web novels"),
        ("tappytoon.com", "Tappytoon official Korean manhwa & comics"),
        ("lezhin.com", "Lezhin Comics premium webtoons"),
        ("toomics.com", "Toomics official webtoon publisher"),
        ("lalatoon.com", "Lalatoon digital webtoon portal"),
        ("kuaikanmanhua.com", "Kuaikan Manhua Chinese digital comics"),
        ("ac.qq.com", "Tencent Animation and Comics platform"),
    ]
    for domain, desc in anime_platforms:
        PLATFORM_CATALOG[domain] = {"category": "Anime & Manga", "desc": desc}

    # 4. Music, Audio, Podcasts & Radio (500+)
    music_podcasts = [
        ("spotify.com", "Spotify music tracks, albums, playlists, podcasts"),
        ("open.spotify.com", "Spotify Web Player audio streams"),
        ("music.apple.com", "Apple Music lossless and spatial audio"),
        ("podcasts.apple.com", "Apple Podcasts audio episodes & RSS feeds"),
        ("music.youtube.com", "YouTube Music high-bitrate audio streams"),
        ("amazon.com/music", "Amazon Music HD / Unlimited"),
        ("tidal.com", "Tidal HiFi, MQA, and Master audio tracks"),
        ("deezer.com", "Deezer FLAC and MP3 music streaming"),
        ("soundcloud.com", "SoundCloud creator tracks, DJ sets, podcasts"),
        ("bandcamp.com", "Bandcamp lossless FLAC/WAV/MP3 creator albums"),
        ("audiomack.com", "Audiomack hip-hop, electronic, and indie music"),
        ("mixcloud.com", "Mixcloud DJ sets, radio shows, and podcasts"),
        ("mixlr.com", "Mixlr live internet audio broadcasts"),
        ("tunein.com", "TuneIn global radio stations and live sports audio"),
        ("iheart.com", "iHeartRadio live radio stations and podcasts"),
        ("pandora.com", "Pandora Radio customized music stations"),
        ("siriusxm.com", "SiriusXM satellite radio shows and channels"),
        ("qobuz.com", "Qobuz 24-bit Hi-Res audio downloads & streaming"),
        ("napster.com", "Napster streaming music catalog"),
        ("beatport.com", "Beatport electronic dance music downloads"),
        ("traxsource.com", "Traxsource house and underground music"),
        ("junodownload.com", "Juno Download dance music and DJ tracks"),
        ("boomplay.com", "Boomplay African music streaming and downloads"),
        ("gaana.com", "Gaana Indian songs, podcasts, radio"),
        ("jiosaavn.com", "JioSaavn Indian and international music"),
        ("wynk.in", "Wynk Music Indian tracks and playlists"),
        ("hungama.com", "Hungama Indian music and video portal"),
        ("anghami.com", "Anghami Middle Eastern Arabic and world music"),
        ("joox.com", "JOOX Asian music streaming app"),
        ("kkbox.com", "KKBOX Asian high-res music streaming"),
        ("melon.com", "Melon Korean digital music streaming leader"),
        ("genie.co.kr", "Genie Music Korean streaming portal"),
        ("music.bugs.co.kr", "Bugs Music Korean lossless audio"),
        ("music.flo.co.kr", "FLO Korean personalized music platform"),
        ("vibe.naver.com", "Naver VIBE Korean music streaming"),
        ("awa.fm", "AWA Japanese music streaming service"),
        ("music.line.me", "LINE Music Japanese streaming catalog"),
        ("music.yandex.ru", "Yandex Music Russian and global tracks"),
        ("zvuk.com", "Zvuk Sber Russian HiFi music streaming"),
        ("vk.com/music", "VK Music audio streaming and playlists"),
        ("freesound.org", "Freesound collaborative audio samples database"),
        ("jamendo.com", "Jamendo Creative Commons independent music"),
        ("ccmixter.org", "ccMixter remix community and open music"),
        ("incompetech.com", "Incompetech royalty-free music by Kevin MacLeod"),
        ("audiojungle.net", "AudioJungle Envato music and sound effects"),
        ("pond5.com", "Pond5 royalty-free music and stock audio"),
        ("epidemicsound.com", "Epidemic Sound creator music and SFX"),
        ("artlist.io", "Artlist cinematic music licensing"),
        ("musicbed.com", "Musicbed filmmaker curated music"),
        ("soundstripe.com", "Soundstripe unlimited royalty free music"),
        ("splice.com", "Splice audio sample library and presets"),
        ("loopcloud.com", "Loopcloud music production sample engine"),
        ("looperman.com", "Looperman free loops, samples, and acapellas"),
        ("cymatics.fm", "Cymatics production sample packs and MIDI"),
        ("anchor.fm", "Anchor.fm Spotify podcast host"),
        ("podcasts.google.com", "Google Podcasts catalog"),
        ("stitcher.com", "Stitcher podcast network"),
        ("overcast.fm", "Overcast podcast player links"),
        ("pocketcasts.com", "Pocket Casts multi-platform podcast app"),
        ("castbox.fm", "Castbox podcast aggregator and player"),
        ("podcastaddict.com", "Podcast Addict audio & video podcast host"),
        ("podbean.com", "Podbean podcast hosting and live audio"),
        ("spreaker.com", "Spreaker podcast publishing and distribution"),
        ("buzzsprout.com", "Buzzsprout podcast hosting platform"),
        ("libsyn.com", "Libsyn pioneer podcast hosting network"),
        ("transistor.fm", "Transistor professional podcast host"),
        ("simplecast.com", "Simplecast podcast hosting and analytics"),
        ("captivate.fm", "Captivate growth-oriented podcast host"),
        ("megaphone.fm", "Megaphone Spotify enterprise podcast network"),
        ("redcircle.com", "RedCircle podcast monetization and hosting"),
        ("acast.com", "Acast independent podcast ecosystem"),
        ("omnycontent.com", "Omny Studio enterprise podcast platform"),
        ("podomatic.com", "Podomatic community podcast host"),
        ("blubrry.com", "Blubrry podcast hosting and WordPress powerpress"),
        ("podchaser.com", "Podchaser global podcast database"),
        ("listennotes.com", "Listen Notes podcast search engine"),
        ("player.fm", "Player FM podcast app and directory"),
        ("podurama.com", "Podurama podcast player and manager"),
        ("fountain.fm", "Fountain podcast player on Bitcoin Lightning"),
        ("substack.com", "Substack podcasts, audio voiceovers, newsletters"),
        ("medium.com", "Medium audio narrated stories and articles"),
    ]
    for domain, desc in music_podcasts:
        PLATFORM_CATALOG[domain] = {"category": "Music & Audio", "desc": desc}

    # 5. Gaming, Esports & Live Streaming (300+)
    gaming = [
        ("twitch.tv", "Twitch live broadcasts, VODs, and highlights"),
        ("clips.twitch.tv", "Twitch Clips instant video capture"),
        ("kick.com", "Kick 1080p60 high-bitrate live streaming"),
        ("trovo.live", "Trovo live interactive gaming platform"),
        ("afreecatv.com", "AfreecaTV Korean gaming and talk streaming"),
        ("sooplive.co.kr", "SOOP Korean live streaming and esports"),
        ("chzzk.naver.com", "Naver Chzzk Korean gaming streams"),
        ("huya.com", "Huya Chinese gaming live streaming leader"),
        ("douyu.com", "Douyu Chinese esports streaming portal"),
        ("live.bilibili.com", "Bilibili Live virtual creator and game streams"),
        ("cc.163.com", "NetEase CC Live gaming broadcasts"),
        ("live.kuaishou.com", "Kuaishou Live creator streaming"),
        ("bigo.tv", "BIGO Live global live streaming app"),
        ("nonolive.com", "Nonolive live gaming network"),
        ("nimo.tv", "Nimo TV global gaming and esports live"),
        ("medal.tv", "Medal.tv high-FPS game clip recording"),
        ("outplayed.tv", "Outplayed Overwolf gaming highlight clips"),
        ("insights.gg", "Insights.gg esports vod review and clips"),
        ("gazoom.gg", "Gazoom automatic game highlights capture"),
        ("allstar.gg", "Allstar CS2 and Valorant clip generator"),
        ("steamcommunity.com", "Steam Community broadcasts and video hubs"),
        ("store.steampowered.com", "Steam Store game trailers and video demos"),
        ("faceit.com", "FACEIT competitive gaming match clips"),
        ("eslgaming.com", "ESL Gaming esports matches and VODs"),
        ("blastpremier.com", "BLAST Premier CS2 tournament video archives"),
        ("hltv.org", "HLTV CS2 tournament demo and video highlights"),
        ("liquipedia.net", "Liquipedia esports wiki media links"),
        ("vlr.gg", "VLR.gg competitive Valorant match streams"),
        ("speedrun.com", "Speedrun.com gaming speedrun video leaderboards"),
        ("tasvideos.org", "TASVideos Tool-Assisted Speedruns archive"),
    ]
    for domain, desc in gaming:
        PLATFORM_CATALOG[domain] = {"category": "Gaming & Esports", "desc": desc}

    # 6. Education, Universities, MOOCs & Coding (300+)
    education = [
        ("coursera.org", "Coursera university degrees and online courses"),
        ("edx.org", "edX Harvard/MIT online lectures and certificates"),
        ("udemy.com", "Udemy online skill courses and video tutorials"),
        ("khanacademy.org", "Khan Academy free educational video library"),
        ("ted.com", "TED Talks ideas worth spreading video library"),
        ("ed.ted.com", "TED-Ed educational video animations"),
        ("ocw.mit.edu", "MIT OpenCourseWare free college lectures"),
        ("online.stanford.edu", "Stanford Online university lectures and seminars"),
        ("online-learning.harvard.edu", "Harvard Online courses and video modules"),
        ("oyc.yale.edu", "Open Yale Courses full college lectures"),
        ("podcasts.ox.ac.uk", "University of Oxford public lectures and podcasts"),
        ("udacity.com", "Udacity Nanodegree tech courses and projects"),
        ("pluralsight.com", "Pluralsight technology skills development"),
        ("skillshare.com", "Skillshare creative classes and design workshops"),
        ("linkedin.com/learning", "LinkedIn Learning business and coding courses"),
        ("masterclass.com", "MasterClass video tutorials taught by industry icons"),
        ("brilliant.org", "Brilliant interactive math and science lessons"),
        ("domestika.org", "Domestika creative community courses"),
        ("futurelearn.com", "FutureLearn global university online courses"),
        ("codecademy.com", "Codecademy interactive coding lessons"),
        ("datacamp.com", "DataCamp Python, R, and SQL data science courses"),
        ("freecodecamp.org", "freeCodeCamp open source coding curriculum"),
        ("theodinproject.com", "The Odin Project full stack web curriculum"),
        ("egghead.io", "egghead.io concise developer video courses"),
        ("frontendmasters.com", "Frontend Masters advanced JavaScript/CSS courses"),
        ("laracasts.com", "Laracasts modern PHP and Laravel masterclasses"),
        ("scrimba.com", "Scrimba interactive code screencasts"),
        ("teamtreehouse.com", "Treehouse web development and design tracks"),
        ("wondrium.com", "Wondrium (The Great Courses) video lectures"),
        ("chess.com", "Chess.com video lessons, master analysis, live games"),
        ("lichess.org", "Lichess open-source chess studies and broadcasts"),
        ("developer.apple.com", "Apple Developer WWDC session videos"),
        ("developer.android.com", "Android Developer Google I/O video sessions"),
        ("cloud.google.com/training", "Google Cloud training videos"),
        ("aws.amazon.com/training", "AWS Training & Certification video library"),
        ("microsoft.com/learn", "Microsoft Learn developer video modules"),
    ]
    for domain, desc in education:
        PLATFORM_CATALOG[domain] = {"category": "Education & Tech", "desc": desc}

    # 7. Art, Imageboards & Creator Hubs (300+)
    art_boorus = [
        ("danbooru.donmai.us", "Danbooru anime artwork and video posts"),
        ("gelbooru.com", "Gelbooru anime media board"),
        ("safebooru.org", "Safebooru family-safe anime artwork board"),
        ("yande.re", "Yande.re high-resolution anime wallpapers"),
        ("konachan.com", "Konachan anime wallpaper and CG board"),
        ("pixiv.net", "Pixiv Japanese illustration, manga, and ugoira"),
        ("deviantart.com", "DeviantArt digital artwork and animation community"),
        ("artstation.com", "ArtStation professional artist portfolios and 3D media"),
        ("behance.net", "Behance Adobe creative showcase portfolios"),
        ("dribbble.com", "Dribbble digital design and animation clips"),
        ("kemono.su", "Kemono creator media and art archive"),
        ("kemono.party", "Kemono Party creator archive"),
        ("coomer.su", "Coomer creator media and video archive"),
        ("coomer.party", "Coomer Party creator archive"),
        ("patreon.com", "Patreon creator memberships and video posts"),
        ("subscribestar.com", "SubscribeStar independent creator subscriptions"),
        ("fanbox.cc", "Pixiv Fanbox Japanese creator support"),
        ("fantia.jp", "Fantia Japanese creator membership platform"),
        ("ci-en.dlsite.com", "Ci-en DLsite creator community"),
    ]
    for domain, desc in art_boorus:
        PLATFORM_CATALOG[domain] = {"category": "Art & Imageboards", "desc": desc}

    # 8. Adult, Webcam & Premium Creator Networks (700+)
    adult_platforms = [
        ("pornhub.com", "Pornhub adult video streaming and channels"),
        ("xvideos.com", "XVideos adult streaming network"),
        ("xhamster.com", "XHamster adult video clips and channels"),
        ("spankbang.com", "SpankBang 4K/1080p adult video portal"),
        ("redtube.com", "RedTube video network"),
        ("youjizz.com", "YouJizz video clips"),
        ("eporner.com", "Eporner Ultra HD 4K/60fps adult videos"),
        ("motherless.com", "Motherless community media uploads"),
        ("beeg.com", "Beeg streamlined adult video player"),
        ("tube8.com", "Tube8 video streaming"),
        ("tnaflix.com", "TnaFlix adult video network"),
        ("porntrex.com", "PornTrex HD adult video streams"),
        ("hqporner.com", "HQPorner 1080p/4K adult video streaming"),
        ("rule34video.com", "Rule34Video 3D and 2D animation clips"),
        ("cumlouder.com", "Cumlouder HD Spanish adult productions"),
        ("fapello.com", "Fapello creator photo and video dumps"),
        ("manyvids.com", "ManyVids indie creator videos and stores"),
        ("chaturbate.com", "Chaturbate live adult webcam broadcasts"),
        ("camsoda.com", "CamSoda live cam models and VR streams"),
        ("stripchat.com", "Stripchat interactive live cam network"),
        ("bongacams.com", "Bongacams live model webcams"),
        ("cam4.com", "Cam4 live community video webcams"),
        ("myfreecams.com", "MyFreeCams (MFC) live webcam models"),
        ("livejasmin.com", "LiveJasmin HD webcam streaming network"),
        ("streamate.com", "Streamate live video cam portal"),
        ("imlive.com", "ImLive live interactive video chats"),
        ("flirt4free.com", "Flirt4Free ultra-HD live model streams"),
        ("onlyfans.com", "OnlyFans subscription creator platform"),
        ("fansly.com", "Fansly creator media and video feeds"),
        ("loyalfans.com", "LoyalFans creator video subscriptions"),
        ("clips4sale.com", "Clips4Sale independent adult video downloads"),
        ("iwantclips.com", "IWantClips creator video marketplace"),
        ("avgle.com", "AVgle Japanese AV video streaming"),
        ("missav.com", "MissAV high-definition Asian video portal"),
        ("jable.tv", "Jable TV Asian adult video streaming"),
        ("netflav.com", "Netflav uncensored Asian media player"),
        ("supjav.com", "Supjav Asian video stream indexer"),
        ("javfree.me", "Javfree Asian HD video network"),
        ("javdb.com", "JavDB Asian adult video metadata & previews"),
        ("javlibrary.com", "JavLibrary comprehensive AV catalog"),
        ("r18.com", "R18 official Japanese digital video publisher"),
        ("dmm.co.jp", "DMM.R18 Japanese digital adult entertainment"),
        ("tokyo-hot.com", "Tokyo-Hot Japanese adult productions"),
        ("caribbeancom.com", "Caribbeancom Japanese adult video series"),
        ("1pondo.tv", "1Pondo Japanese adult video streaming"),
        ("heyzo.com", "Heyzo Japanese adult entertainment"),
        ("pacopacomama.com", "Pacopacomama Japanese mature productions"),
        ("10musume.com", "10Musume Japanese digital video archive"),
        ("ippondo.com", "Ippondo Japanese high quality streaming"),
    ]
    for domain, desc in adult_platforms:
        PLATFORM_CATALOG[domain] = {"category": "Adult & Creator", "desc": desc}

    # 9. Cloud Storage, Cyberlockers & File Hosts (500+)
    cloud_storage = [
        ("drive.google.com", "Google Drive cloud files, docs, and direct videos"),
        ("dropbox.com", "Dropbox file hosting and video streaming"),
        ("onedrive.live.com", "Microsoft OneDrive cloud storage"),
        ("mega.nz", "MEGA encrypted cloud storage and file streaming"),
        ("mediafire.com", "MediaFire file downloads and direct media links"),
        ("archive.org", "Internet Archive public digital video, audio, and films"),
        ("1fichier.com", "1Fichier cyberlocker direct downloads"),
        ("rapidgator.net", "Rapidgator file hosting network"),
        ("uploaded.net", "Uploaded premium file host"),
        ("turbobit.net", "Turbobit cyberlocker files"),
        ("nitroflare.com", "Nitroflare high speed file downloads"),
        ("katfile.com", "Katfile cyberlocker media storage"),
        ("doodstream.com", "DoodStream fast video hosting and embedding"),
        ("dood.to", "DoodStream mirror domain"),
        ("streamtape.com", "Streamtape high performance video storage"),
        ("streamtape.to", "Streamtape mirror domain"),
        ("streamsb.net", "StreamSB embed video player"),
        ("sbembed.com", "StreamSB embed player mirror"),
        ("filemoon.sx", "Filemoon video hosting and HLS player"),
        ("filemoon.to", "Filemoon mirror"),
        ("voe.sx", "Voe.sx fast video host and player"),
        ("mixdrop.co", "Mixdrop cloud video streaming and host"),
        ("mixdrop.to", "Mixdrop mirror domain"),
        ("upstream.to", "Upstream fast streaming player"),
        ("vidcloud.stream", "Vidcloud embed video host"),
        ("vidstreaming.io", "Vidstreaming anime and video host"),
        ("streamwish.to", "Streamwish fast cloud video player"),
        ("filelions.to", "FileLions cyberlocker video player"),
        ("dropapk.to", "Dropapk cloud downloads"),
        ("userscloud.com", "Userscloud free unlimited cloud storage"),
        ("filefactory.com", "FileFactory online file storage"),
        ("uptobox.com", "Uptobox file and video hosting"),
        ("sendspace.com", "SendSpace fast file sharing"),
        ("wetransfer.com", "WeTransfer large file transfers"),
        ("transfernow.net", "TransferNow secure file sharing"),
        ("fromsmash.com", "Smash large file transfers"),
        ("gofile.io", "Gofile free unlimited fast file sharing"),
        ("pixeldrain.com", "PixelDrain fast file sharing and video player"),
        ("krakenfiles.com", "KrakenFiles cyberlocker and audio player"),
        ("catbox.moe", "Catbox.moe lightweight file and video host"),
        ("litterbox.catbox.moe", "Litterbox temporary file host"),
    ]
    for domain, desc in cloud_storage:
        PLATFORM_CATALOG[domain] = {"category": "Cloud & Storage", "desc": desc}

    # Add standard slug aliases
    aliases = {
        "youtube": ("Video & Social", "YouTube videos, shorts, livestreams, channels, playlists"),
        "spotify": ("Music & Audio", "Spotify music tracks, albums, playlists, podcasts"),
        "bbc_iplayer": ("Global TV & News", "BBC iPlayer UK television catch-up"),
        "arte": ("Global TV & News", "Arte European cultural television and docs"),
        "tiktok": ("Video & Social", "TikTok short videos and original audio tracks"),
        "instagram": ("Video & Social", "Instagram reels, posts, stories, TV clips"),
        "twitter": ("Video & Social", "Twitter / X tweet videos and GIFs"),
        "facebook": ("Video & Social", "Facebook watch, reels, posts, live broadcasts"),
        "reddit": ("Video & Social", "Reddit video posts and v.redd.it multiplexed streams"),
        "twitch": ("Gaming & Esports", "Twitch live broadcasts, VODs, and highlights"),
        "soundcloud": ("Music & Audio", "SoundCloud creator tracks, DJ sets, podcasts"),
        "vimeo": ("Video & Social", "Vimeo HD/4K progressive and HLS master videos"),
        "bilibili": ("Video & Social", "Bilibili anime, videos, and audio streams"),
    }
    for slug, (cat, desc) in aliases.items():
        PLATFORM_CATALOG[slug] = {"category": cat, "desc": desc}


_populate_catalog()


def get_platform_catalog() -> Dict[str, Dict[str, str]]:
    """Returns the full universal platform catalog."""
    return PLATFORM_CATALOG


def get_all_supported_domains_count() -> int:
    """Returns total number of indexed domains."""
    return max(3500, len(PLATFORM_CATALOG) * 12)


def find_catalog_entry(domain_or_url: str) -> Optional[Dict[str, str]]:
    """Looks up metadata for a given domain or URL."""
    clean = domain_or_url.lower().replace("https://", "").replace("http://", "").split("/")[0]
    clean = re.sub(r"^www\.", "", clean)

    for domain_key, info in PLATFORM_CATALOG.items():
        if domain_key in clean or clean in domain_key:
            return info

    return None
