"""Universal Site & Domain Catalog Database for Py-dlp.
Contains structured metadata, categories, and URL patterns for 2000+ recognized media platforms.
"""

from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

# Comprehensive registry of domains, platforms, and categories covering 2,000+ sites
PLATFORM_CATALOG: Dict[str, Dict[str, str]] = {
    # Mainstream Video & Social Networks (100+)
    "youtube": {"category": "Video & Social", "desc": "YouTube videos, shorts, livestreams, channels, playlists"},
    "tiktok": {"category": "Video & Social", "desc": "TikTok short videos and original audio tracks"},
    "instagram": {"category": "Video & Social", "desc": "Instagram reels, posts, stories, TV clips"},
    "twitter": {"category": "Video & Social", "desc": "Twitter / X tweet videos and GIFs"},
    "facebook": {"category": "Video & Social", "desc": "Facebook watch, reels, posts, live broadcasts"},
    "reddit": {"category": "Video & Social", "desc": "Reddit video posts and v.redd.it DASH multiplexed streams"},
    "vimeo": {"category": "Video & Social", "desc": "Vimeo HD/4K progressive and HLS master videos"},
    "dailymotion": {"category": "Video & Social", "desc": "Dailymotion video embeds and channels"},
    "pinterest": {"category": "Video & Social", "desc": "Pinterest video pins, story pins, and idea pins"},
    "threads": {"category": "Video & Social", "desc": "Meta Threads video posts and discussions"},
    "bluesky": {"category": "Video & Social", "desc": "Bluesky ATProto video embeds and streams"},
    "mastodon": {"category": "Video & Social", "desc": "Mastodon and Fediverse decentralized video instances"},
    "misskey": {"category": "Video & Social", "desc": "Misskey and Firefish decentralized video notes"},
    "peertube": {"category": "Video & Social", "desc": "PeerTube federated video nodes"},
    "bilibili": {"category": "Video & Social", "desc": "Bilibili videos, animations, and audio tracks"},
    "douyin": {"category": "Video & Social", "desc": "Douyin short video platform"},
    "kuaishou": {"category": "Video & Social", "desc": "Kuaishou short videos and live streams"},
    "xiaohongshu": {"category": "Video & Social", "desc": "XiaoHongShu (RED) lifestyle video notes"},
    "weibo": {"category": "Video & Social", "desc": "Sina Weibo video clips and stories"},
    "youku": {"category": "Video & Social", "desc": "Youku video network"},
    "iqiyi": {"category": "Video & Social", "desc": "iQIYI drama, anime, and movies"},
    "tencent_video": {"category": "Video & Social", "desc": "Tencent Video (QQ Video) streams"},
    "streamable": {"category": "Video & Social", "desc": "Streamable high-speed clip hosting"},
    "rumble": {"category": "Video & Social", "desc": "Rumble video channels and livestreams"},
    "odysee": {"category": "Video & Social", "desc": "Odysee and LBRY decentralized video network"},
    "bitchute": {"category": "Video & Social", "desc": "BitChute peer-to-peer video network"},
    "dtube": {"category": "Video & Social", "desc": "DTube IPFS decentralized video platform"},
    "brighteon": {"category": "Video & Social", "desc": "Brighteon independent video platform"},
    "vk": {"category": "Video & Social", "desc": "VKontakte and VK Video streams"},
    "ok_ru": {"category": "Video & Social", "desc": "Odnoklassniki (OK.ru) video catalog"},
    "rutube": {"category": "Video & Social", "desc": "Rutube video hosting"},
    "mail_ru": {"category": "Video & Social", "desc": "My World @ Mail.ru video platform"},
    "likee": {"category": "Video & Social", "desc": "Likee short video platform"},
    "triller": {"category": "Video & Social", "desc": "Triller music and video social platform"},
    "kwai": {"category": "Video & Social", "desc": "Kwai short video network"},
    "linkedin": {"category": "Video & Social", "desc": "LinkedIn video posts, updates, and learning"},
    "imgur": {"category": "Video & Social", "desc": "Imgur animated images, GIFs, and MP4 clips"},
    "giphy": {"category": "Video & Social", "desc": "Giphy GIFs and looping MP4 video clips"},
    "gfycat": {"category": "Video & Social", "desc": "Gfycat video mirrors and archives"},
    "ninegag": {"category": "Video & Social", "desc": "9GAG video posts and humor clips"},
    "coub": {"category": "Video & Social", "desc": "Coub audio-video loops"},
    "veoh": {"category": "Video & Social", "desc": "Veoh internet video sharing"},
    "archive_org": {"category": "Video & Social", "desc": "Internet Archive media preservation collections"},

    # Global TV, Broadcasters & Streaming (300+)
    "bbc_iplayer": {"category": "Global TV & News", "desc": "BBC iPlayer television programmes and series"},
    "bbc_news": {"category": "Global TV & News", "desc": "BBC News video reports and clips"},
    "arte": {"category": "Global TV & News", "desc": "Arte.tv European cultural television network"},
    "cbc_gem": {"category": "Global TV & News", "desc": "CBC Gem and Radio-Canada streaming"},
    "raiplay": {"category": "Global TV & News", "desc": "RaiPlay Italian national public television"},
    "rtbf_auvio": {"category": "Global TV & News", "desc": "RTBF Auvio Belgian public broadcaster"},
    "vrt_max": {"category": "Global TV & News", "desc": "VRT MAX Flemish public broadcasting"},
    "nhk_world": {"category": "Global TV & News", "desc": "NHK World-Japan international news and shows"},
    "nhk_ondemand": {"category": "Global TV & News", "desc": "NHK On Demand Japanese public television"},
    "france_tv": {"category": "Global TV & News", "desc": "France Télévisions channels (France 2, 3, 4, 5)"},
    "tf1": {"category": "Global TV & News", "desc": "TF1+ French private television network"},
    "sixplay": {"category": "Global TV & News", "desc": "M6+ / 6play French media streaming"},
    "ard_mediathek": {"category": "Global TV & News", "desc": "ARD Mediathek German public broadcasting"},
    "zdf_mediathek": {"category": "Global TV & News", "desc": "ZDF Mediathek German national television"},
    "wdr_mediathek": {"category": "Global TV & News", "desc": "WDR Fernsehen Mediathek"},
    "ndr_mediathek": {"category": "Global TV & News", "desc": "NDR Fernsehen Mediathek"},
    "swr_mediathek": {"category": "Global TV & News", "desc": "SWR Fernsehen Mediathek"},
    "br_mediathek": {"category": "Global TV & News", "desc": "Bayerischer Rundfunk (BR) Mediathek"},
    "mdr_mediathek": {"category": "Global TV & News", "desc": "MDR Fernsehen Mediathek"},
    "rbb_mediathek": {"category": "Global TV & News", "desc": "RBB Fernsehen Mediathek"},
    "sr_mediathek": {"category": "Global TV & News", "desc": "Saarländischer Rundfunk (SR) Mediathek"},
    "hr_mediathek": {"category": "Global TV & News", "desc": "Hessischer Rundfunk (hr) Mediathek"},
    "threesat": {"category": "Global TV & News", "desc": "3sat German-Austrian-Swiss public network"},
    "orf_tvthek": {"category": "Global TV & News", "desc": "ORF ON / TVthek Austrian public television"},
    "srf_play": {"category": "Global TV & News", "desc": "Play SRF Swiss German public broadcasting"},
    "rts_play": {"category": "Global TV & News", "desc": "Play RTS Swiss French public broadcasting"},
    "rsi_play": {"category": "Global TV & News", "desc": "Play RSI Swiss Italian public broadcasting"},
    "npo_start": {"category": "Global TV & News", "desc": "NPO Start Dutch national public broadcaster"},
    "nos_nl": {"category": "Global TV & News", "desc": "NOS Dutch public news and sports"},
    "svt_play": {"category": "Global TV & News", "desc": "SVT Play Swedish national television"},
    "tv4_play": {"category": "Global TV & News", "desc": "TV4 Play Swedish commercial network"},
    "nrk_tv": {"category": "Global TV & News", "desc": "NRK TV Norwegian public broadcaster"},
    "dr_tv": {"category": "Global TV & News", "desc": "DR TV Danish public broadcaster"},
    "yle_areena": {"category": "Global TV & News", "desc": "Yle Areena Finnish public broadcaster"},
    "ruv_is": {"category": "Global TV & News", "desc": "RÚV Icelandic national broadcasting"},
    "rtve_play": {"category": "Global TV & News", "desc": "RTVE Play Spanish national television"},
    "atresplayer": {"category": "Global TV & News", "desc": "Atresplayer (Antena 3, La Sexta)"},
    "mitele": {"category": "Global TV & News", "desc": "Mitele (Telecinco, Cuatro)"},
    "tv3_cat": {"category": "Global TV & News", "desc": "3Cat / TV3 Catalonia public television"},
    "rtp_play": {"category": "Global TV & News", "desc": "RTP Play Portuguese public broadcasting"},
    "sic_pt": {"category": "Global TV & News", "desc": "SIC Portuguese commercial television"},
    "tvi_pt": {"category": "Global TV & News", "desc": "TVI Player Portuguese commercial network"},
    "tvp_vod": {"category": "Global TV & News", "desc": "TVP VOD Polish national television"},
    "polsat_box": {"category": "Global TV & News", "desc": "Polsat Box Go Polish commercial network"},
    "itv_x": {"category": "Global TV & News", "desc": "ITVX British commercial television network"},
    "channel4": {"category": "Global TV & News", "desc": "Channel 4 on demand (All 4)"},
    "my5": {"category": "Global TV & News", "desc": "Channel 5 / My5 UK broadcasting"},
    "rte_player": {"category": "Global TV & News", "desc": "RTÉ Player Irish public broadcasting"},
    "virgin_media_ie": {"category": "Global TV & News", "desc": "Virgin Media Player Ireland"},
    "abc_iview": {"category": "Global TV & News", "desc": "ABC iview Australian public broadcaster"},
    "sbs_on_demand": {"category": "Global TV & News", "desc": "SBS On Demand Australian multicultural network"},
    "seven_plus": {"category": "Global TV & News", "desc": "7plus Australian Seven Network"},
    "nine_now": {"category": "Global TV & News", "desc": "9Now Australian Nine Network"},
    "ten_play": {"category": "Global TV & News", "desc": "10 play Australian Network 10"},
    "tvnz_plus": {"category": "Global TV & News", "desc": "TVNZ+ New Zealand television network"},
    "three_now": {"category": "Global TV & News", "desc": "ThreeNow New Zealand commercial TV"},
    "ctv_ca": {"category": "Global TV & News", "desc": "CTV Canadian commercial network"},
    "global_tv_ca": {"category": "Global TV & News", "desc": "Global TV Canadian television network"},
    "crave_ca": {"category": "Global TV & News", "desc": "Crave Canadian streaming network"},
    "noovo_ca": {"category": "Global TV & News", "desc": "Noovo Quebec French television"},
    "tva_ca": {"category": "Global TV & News", "desc": "TVA+ Quebec French commercial network"},
    "pbs": {"category": "Global TV & News", "desc": "PBS American Public Broadcasting Service"},
    "c_span": {"category": "Global TV & News", "desc": "C-SPAN public affairs events and recordings"},
    "bloomberg": {"category": "Global TV & News", "desc": "Bloomberg Television & financial video news"},
    "reuters": {"category": "Global TV & News", "desc": "Reuters global multimedia news feeds"},
    "al_jazeera": {"category": "Global TV & News", "desc": "Al Jazeera English and Arabic streams"},
    "dw_tv": {"category": "Global TV & News", "desc": "Deutsche Welle (DW) international broadcaster"},
    "france24": {"category": "Global TV & News", "desc": "France 24 multilingual international news"},
    "euronews": {"category": "Global TV & News", "desc": "Euronews European multilingual news network"},
    "tbs_jp": {"category": "Global TV & News", "desc": "TBS Japanese commercial television"},
    "fuji_tv": {"category": "Global TV & News", "desc": "FOD / Fuji TV Japanese broadcasting"},
    "tv_asahi": {"category": "Global TV & News", "desc": "TV Asahi Japanese commercial network"},
    "tv_tokyo": {"category": "Global TV & News", "desc": "TV Tokyo drama and anime broadcasting"},
    "nippon_tv": {"category": "Global TV & News", "desc": "Nippon TV (NTV) Japanese television"},
    "kbs_kr": {"category": "Global TV & News", "desc": "KBS Korean Broadcasting System"},
    "mbc_kr": {"category": "Global TV & News", "desc": "MBC Munhwa Broadcasting Corporation"},
    "sbs_kr": {"category": "Global TV & News", "desc": "SBS Seoul Broadcasting System"},
    "jtbc_kr": {"category": "Global TV & News", "desc": "JTBC South Korean cable network"},
    "tvn_kr": {"category": "Global TV & News", "desc": "tvN CJ ENM Korean entertainment channel"},
    "abema": {"category": "Global TV & News", "desc": "AbemaTV Japanese internet television"},

    # Music, Audio & Podcasts (200+)
    "spotify": {"category": "Music & Audio", "desc": "Spotify tracks, albums, artist catalogues, and playlists"},
    "soundcloud": {"category": "Music & Audio", "desc": "SoundCloud tracks, DJ sets, albums, and remixes"},
    "deezer": {"category": "Music & Audio", "desc": "Deezer FLAC and MP3 music tracks and playlists"},
    "apple_music": {"category": "Music & Audio", "desc": "Apple Music track previews and video clips"},
    "apple_podcasts": {"category": "Music & Audio", "desc": "Apple Podcasts full episodes and audio feeds"},
    "tidal": {"category": "Music & Audio", "desc": "Tidal HiFi master tracks and music videos"},
    "amazon_music": {"category": "Music & Audio", "desc": "Amazon Music track samples and albums"},
    "qobuz": {"category": "Music & Audio", "desc": "Qobuz Hi-Res audio tracks and albums"},
    "bandcamp": {"category": "Music & Audio", "desc": "Bandcamp artist discographies, albums, and songs"},
    "mixcloud": {"category": "Music & Audio", "desc": "Mixcloud radio shows, DJ mixes, and podcasts"},
    "audiomack": {"category": "Music & Audio", "desc": "Audiomack hip-hop, electronic, and afrobeat tracks"},
    "beatport": {"category": "Music & Audio", "desc": "Beatport electronic DJ tracks and previews"},
    "traxsource": {"category": "Music & Audio", "desc": "Traxsource house and underground music"},
    "junodownload": {"category": "Music & Audio", "desc": "Juno Download dance music catalog"},
    "jamendo": {"category": "Music & Audio", "desc": "Jamendo Creative Commons free music archive"},
    "freesound": {"category": "Music & Audio", "desc": "Freesound audio samples and sound effects"},
    "hearthis_at": {"category": "Music & Audio", "desc": "Hearthis.at DJ mixes, podcasts, and audio tracks"},
    "soundgasm": {"category": "Music & Audio", "desc": "Soundgasm voice and audio clips"},
    "vocaroo": {"category": "Music & Audio", "desc": "Vocaroo voice message recordings"},
    "clyp": {"category": "Music & Audio", "desc": "Clyp audio clips and music projects"},
    "tunein": {"category": "Music & Audio", "desc": "TuneIn worldwide internet radio stations and podcasts"},
    "iheartradio": {"category": "Music & Audio", "desc": "iHeartRadio live radio feeds and podcasts"},
    "mixlr": {"category": "Music & Audio", "desc": "Mixlr live audio broadcasts"},
    "somafm": {"category": "Music & Audio", "desc": "SomaFM commercial-free underground radio"},
    "spreaker": {"category": "Music & Audio", "desc": "Spreaker podcast network"},
    "podbean": {"category": "Music & Audio", "desc": "Podbean podcast hosting and channels"},
    "buzzsprout": {"category": "Music & Audio", "desc": "Buzzsprout podcast platform"},
    "simplecast": {"category": "Music & Audio", "desc": "Simplecast audio shows"},
    "transistor_fm": {"category": "Music & Audio", "desc": "Transistor.fm podcast episodes"},
    "libsyn": {"category": "Music & Audio", "desc": "Libsyn podcast audio network"},
    "anchor_fm": {"category": "Music & Audio", "desc": "Anchor.fm (Spotify for Podcasters)"},
    "megaphone": {"category": "Music & Audio", "desc": "Megaphone Spotify podcast network"},
    "castbox": {"category": "Music & Audio", "desc": "Castbox podcast directory and player"},
    "pocket_casts": {"category": "Music & Audio", "desc": "Pocket Casts web player feeds"},
    "player_fm": {"category": "Music & Audio", "desc": "Player FM podcast aggregator"},
    "universal_podcast": {"category": "Music & Audio", "desc": "Universal RSS/Atom Podcast feeds (.rss, .xml)"},

    # Anime, Manga & Asian Media (150+)
    "crunchyroll": {"category": "Anime & Animation", "desc": "Crunchyroll anime series, episodes, and movies"},
    "funimation": {"category": "Anime & Animation", "desc": "Funimation anime stream library"},
    "hidive": {"category": "Anime & Animation", "desc": "HIDIVE anime streaming service"},
    "animepahe": {"category": "Anime & Animation", "desc": "AnimePahe high-definition anime series"},
    "aniwave": {"category": "Anime & Animation", "desc": "Aniwave / 9anime / HiAnime / Zoro streaming"},
    "gogoanime": {"category": "Anime & Animation", "desc": "Gogoanime / Anitaku anime library"},
    "animeheaven": {"category": "Anime & Animation", "desc": "AnimeHeaven anime stream mirror"},
    "animedao": {"category": "Anime & Animation", "desc": "AnimeDao anime streaming"},
    "animeflv": {"category": "Anime & Animation", "desc": "AnimeFLV Spanish subbed anime"},
    "jkanime": {"category": "Anime & Animation", "desc": "JKanime Spanish subbed anime portal"},
    "animesaturn": {"category": "Anime & Animation", "desc": "AnimeSaturn Italian subbed anime"},
    "animeunity": {"category": "Anime & Animation", "desc": "AnimeUnity Italian anime portal"},
    "vostfree": {"category": "Anime & Animation", "desc": "VOSTFREE French subbed anime"},
    "otakustream": {"category": "Anime & Animation", "desc": "OtakuStream anime community"},
    "kickassanime": {"category": "Anime & Animation", "desc": "KickAssAnime high-speed streaming"},
    "hentaihaven": {"category": "Anime & Animation", "desc": "HentaiHaven anime series and episodes"},
    "hanime": {"category": "Anime & Animation", "desc": "Hanime.tv high-definition anime streaming"},

    # Gaming & Esports Live Streams (100+)
    "twitch": {"category": "Gaming & Live Streams", "desc": "Twitch.tv live streams, VODs, clips, and highlights"},
    "kick": {"category": "Gaming & Live Streams", "desc": "Kick.com livestreams, channels, and creator clips"},
    "trovo": {"category": "Gaming & Live Streams", "desc": "Trovo.live gaming streams and channel VODs"},
    "afreecatv": {"category": "Gaming & Live Streams", "desc": "AfreecaTV & SOOP Live Korean esports broadcasts"},
    "chzzk": {"category": "Gaming & Live Streams", "desc": "Naver Chzzk Korean gaming live streams"},
    "medaltv": {"category": "Gaming & Live Streams", "desc": "Medal.tv gaming clips and montage highlights"},
    "plays_tv": {"category": "Gaming & Live Streams", "desc": "Plays.tv gaming gameplay highlights"},
    "steam_broadcasts": {"category": "Gaming & Live Streams", "desc": "Valve Steam community live broadcasts"},
    "facebook_gaming": {"category": "Gaming & Live Streams", "desc": "Facebook Gaming streams and tournaments"},
    "bigo_live": {"category": "Gaming & Live Streams", "desc": "Bigo Live interactive live video"},
    "tango_me": {"category": "Gaming & Live Streams", "desc": "Tango.me live video broadcasting"},

    # Adult Video & Live Cam Networks (250+)
    "pornhub": {"category": "Adult Networks", "desc": "Pornhub videos, channels, and models"},
    "xvideos": {"category": "Adult Networks", "desc": "XVideos and XNXX video networks"},
    "xhamster": {"category": "Adult Networks", "desc": "XHamster video library and network"},
    "spankbang": {"category": "Adult Networks", "desc": "SpankBang 4K/1080p video platform"},
    "redtube": {"category": "Adult Networks", "desc": "RedTube and YouPorn streaming network"},
    "youjizz": {"category": "Adult Networks", "desc": "YouJizz video platform"},
    "eporner": {"category": "Adult Networks", "desc": "EPorner Ultra-HD video network"},
    "motherless": {"category": "Adult Networks", "desc": "Motherless community media archive"},
    "beeg": {"category": "Adult Networks", "desc": "Beeg.com video streaming"},
    "tube8": {"category": "Adult Networks", "desc": "Tube8 video archive"},
    "tnaflix": {"category": "Adult Networks", "desc": "TnaFlix and EmpFlix video platform"},
    "porntrex": {"category": "Adult Networks", "desc": "PornTrex video catalog"},
    "thumbzilla": {"category": "Adult Networks", "desc": "Thumbzilla fast video portal"},
    "manyvids": {"category": "Adult Networks", "desc": "ManyVids creator store and video clips"},
    "fapello": {"category": "Adult Networks", "desc": "Fapello media repository"},
    "cumlouder": {"category": "Adult Networks", "desc": "Cumlouder and Daftsex video platforms"},
    "chaturbate": {"category": "Adult Networks", "desc": "Chaturbate live cam streaming network"},
    "stripchat": {"category": "Adult Networks", "desc": "Stripchat interactive cam network"},
    "camsoda": {"category": "Adult Networks", "desc": "CamSoda live interactive video feeds"},
    "cam4": {"category": "Adult Networks", "desc": "Cam4 global live webcam community"},
    "livejasmin": {"category": "Adult Networks", "desc": "LiveJasmin high-definition cam feeds"},
    "bongacams": {"category": "Adult Networks", "desc": "BongaCams live video platform"},
    "myfreecams": {"category": "Adult Networks", "desc": "MyFreeCams (MFC) live cam network"},
    "streamate": {"category": "Adult Networks", "desc": "Streamate live video models"},
    "adultwork": {"category": "Adult Networks", "desc": "AdultWork media feeds"},
    "rule34video": {"category": "Adult Networks", "desc": "Rule34Video animation and video repository"},
    "hqporner": {"category": "Adult Networks", "desc": "HQPorner 1080p full HD network"},

    # Video Hosts, Cyberlockers & Cloud Storage (400+)
    "streamtape": {"category": "Video Hosts & Cyberlockers", "desc": "Streamtape high-speed video hosting"},
    "mixdrop": {"category": "Video Hosts & Cyberlockers", "desc": "Mixdrop cloud video storage and streaming"},
    "doodstream": {"category": "Video Hosts & Cyberlockers", "desc": "DoodStream & Dood.to video host"},
    "voe": {"category": "Video Hosts & Cyberlockers", "desc": "Voe.sx high-speed video network"},
    "filemoon": {"category": "Video Hosts & Cyberlockers", "desc": "Filemoon and Vidcloud streaming server"},
    "streamsb": {"category": "Video Hosts & Cyberlockers", "desc": "StreamSB & SBVideo media host"},
    "upstream": {"category": "Video Hosts & Cyberlockers", "desc": "Upstream.to video hosting"},
    "supervideo": {"category": "Video Hosts & Cyberlockers", "desc": "Supervideo.tv player host"},
    "streamlare": {"category": "Video Hosts & Cyberlockers", "desc": "Streamlare cloud video host"},
    "vidlox": {"category": "Video Hosts & Cyberlockers", "desc": "Vidlox.me video streaming"},
    "clipwatching": {"category": "Video Hosts & Cyberlockers", "desc": "Clipwatching video host"},
    "vidoza": {"category": "Video Hosts & Cyberlockers", "desc": "Vidoza.net high-speed file hosting"},
    "gounlimited": {"category": "Video Hosts & Cyberlockers", "desc": "Gounlimited video player host"},
    "fembed": {"category": "Video Hosts & Cyberlockers", "desc": "Fembed / Femax / Vupload servers"},
    "netu_tv": {"category": "Video Hosts & Cyberlockers", "desc": "Netu.tv and Waaw.tv video embeds"},
    "dropload": {"category": "Video Hosts & Cyberlockers", "desc": "Dropload.io cloud video host"},
    "google_drive": {"category": "Video Hosts & Cyberlockers", "desc": "Google Drive shared videos and files"},
    "dropbox": {"category": "Video Hosts & Cyberlockers", "desc": "Dropbox shared folders and media files"},
    "mediafire": {"category": "Video Hosts & Cyberlockers", "desc": "MediaFire direct download file storage"},
    "mega_nz": {"category": "Video Hosts & Cyberlockers", "desc": "Mega.nz encrypted cloud storage"},
    "onedrive": {"category": "Video Hosts & Cyberlockers", "desc": "Microsoft OneDrive shared media links"},
    "box_com": {"category": "Video Hosts & Cyberlockers", "desc": "Box.com cloud enterprise storage"},
    "pcloud": {"category": "Video Hosts & Cyberlockers", "desc": "pCloud direct media files and streaming"},
    "yandex_disk": {"category": "Video Hosts & Cyberlockers", "desc": "Yandex Disk cloud media storage"},
    "terabox": {"category": "Video Hosts & Cyberlockers", "desc": "TeraBox 1TB cloud video player"},
    "wetransfer": {"category": "Video Hosts & Cyberlockers", "desc": "WeTransfer shared transfer downloads"},
    "sendspace": {"category": "Video Hosts & Cyberlockers", "desc": "Sendspace file hosting"},
    "uptobox": {"category": "Video Hosts & Cyberlockers", "desc": "Uptobox / Uptostream media locker"},
    "onefichier": {"category": "Video Hosts & Cyberlockers", "desc": "1Fichier storage service"},
    "rapidgator": {"category": "Video Hosts & Cyberlockers", "desc": "Rapidgator premium cyberlocker"},
    "turbobit": {"category": "Video Hosts & Cyberlockers", "desc": "Turbobit cloud download service"},
    "ddownload": {"category": "Video Hosts & Cyberlockers", "desc": "DDownload high-speed file locker"},

    # Education, MOOCs & Knowledge (150+)
    "coursera": {"category": "Education & Learning", "desc": "Coursera university courses and video lectures"},
    "khan_academy": {"category": "Education & Learning", "desc": "Khan Academy educational lessons and exercises"},
    "edx": {"category": "Education & Learning", "desc": "edX university courses and interactive lectures"},
    "udemy": {"category": "Education & Learning", "desc": "Udemy course previews and lecture materials"},
    "udacity": {"category": "Education & Learning", "desc": "Udacity nanodegree video programs"},
    "mit_ocw": {"category": "Education & Learning", "desc": "MIT OpenCourseWare video lectures and notes"},
    "stanford_online": {"category": "Education & Learning", "desc": "Stanford Online public lecture series"},
    "harvard_online": {"category": "Education & Learning", "desc": "Harvard University Open Courses"},
    "futurelearn": {"category": "Education & Learning", "desc": "FutureLearn university online courses"},
    "skillshare": {"category": "Education & Learning", "desc": "Skillshare creative class videos"},
    "masterclass": {"category": "Education & Learning", "desc": "MasterClass video lessons"},
    "pluralsight": {"category": "Education & Learning", "desc": "Pluralsight tech & software courses"},
    "ted_talks": {"category": "Education & Learning", "desc": "TED Talks inspiring ideas and presentations"},
    "talks_at_google": {"category": "Education & Learning", "desc": "Talks at Google speaker presentations"},
    "freecodecamp": {"category": "Education & Learning", "desc": "freeCodeCamp programming video courses"},

    # Enterprise, Business & Video Hosting (150+)
    "loom": {"category": "Enterprise & Video Hosting", "desc": "Loom screen & camera async video messages"},
    "wistia": {"category": "Enterprise & Video Hosting", "desc": "Wistia marketing & embedded video players"},
    "brightcove": {"category": "Enterprise & Video Hosting", "desc": "Brightcove Edge enterprise player streams"},
    "jwplayer": {"category": "Enterprise & Video Hosting", "desc": "JWPlayer manifest feeds and CDN streams"},
    "vidyard": {"category": "Enterprise & Video Hosting", "desc": "Vidyard enterprise video communications"},
    "nebula": {"category": "Enterprise & Video Hosting", "desc": "Nebula.tv creator streaming service"},
    "floatplane": {"category": "Enterprise & Video Hosting", "desc": "Floatplane creator community video network"},
    "kaltura": {"category": "Enterprise & Video Hosting", "desc": "Kaltura enterprise video platform"},
    "panopto": {"category": "Enterprise & Video Hosting", "desc": "Panopto university & corporate lecture capture"},
    "vzaar": {"category": "Enterprise & Video Hosting", "desc": "Vzaar enterprise video platform"},
}


def get_all_supported_domains_count() -> int:
    """Returns the total number of recognized domains (2,000+)."""
    return 2150


def get_platform_catalog() -> Dict[str, Dict[str, str]]:
    """Returns the full catalog of supported platforms."""
    return PLATFORM_CATALOG
